baseURL = "http://example.org/"
languageCode = "en-us"
title = "Dakota's Website"
theme = "mytheme"
relativeURLs = true

[menu]
  [[menu.main]]
    identifier = "lions"
    name = "Lions"
    url = "/lion/"
    weight = 100

  [[menu.main]]
    identifier = "giraffe"
    name = "Giraffe"
    url = "/giraffe/"
    weight = 110

    [[menu.main]]
    identifier = "goats"
    name = "Goats"
    url = "/goats/"
    weight = 120